class OperationType:
    LOAD_PRODUCTS = 'LOAD_PRODUCTS'
    UPDATE_PRODUCT_PRICES = 'UPDATE_PRODUCT_PRICES'
    UPDATE_PRODUCT_STOCKS = 'UPDATE_PRODUCT_STOCKS'
    ARCHIVE_PRODUCTS = 'ARCHIVE_PRODUCTS'